### ISSUE TITLE
有个报错找不到原因

### ISSUE THREAD

**Issue by Lailaizb** [tclyjy/handwriting-weapp#2]
Cannot read property 'width' of null;at pages/home/handwriting/handwriting onShow function;at SelectorQuery callback function
TypeError: Cannot read property 'width' of null
    at t.<anonymous> (http://127.0.0.1:45077/appservice/pages/home/components/handwriting/handwriting.js:75:33)
    at Function.<anonymous> (

这一行
_this.canvasWidth = rect.width;

**Comment by tclyjy** [comment]
```
query.select('.handCenter').boundingClientRect(rect => {
      console.log(rect)
      this.canvasWidth = rect.width;
      this.canvasHeight = rect.height;
    }).exec();
```
打印一下看是否获取到了 canvas容器（demo中是<view class="handCenter"></view>），你可以自定义命名。
